#if !defined(AFX_EIGDATAQUEUEITEMW_H__E746E134_B6CC_46EE_A29D_C81655753CD7__INCLUDED_)
#define AFX_EIGDATAQUEUEITEMW_H__E746E134_B6CC_46EE_A29D_C81655753CD7__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CEIGDataQueueItemW wrapper class

class CEIGDataQueueItemW : public COleDispatchDriver
{
public:
	CEIGDataQueueItemW() {}		// Calls COleDispatchDriver default constructor
	CEIGDataQueueItemW(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CEIGDataQueueItemW(const CEIGDataQueueItemW& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetExtUser();
	void SetExtUser(LPCTSTR lpszNewValue);
	CString GetExtJobName();
	void SetExtJobName(LPCTSTR lpszNewValue);
	CString GetExtJobNumber();
	void SetExtJobNumber(LPCTSTR lpszNewValue);
	CString GetInactiveRec();
	void SetInactiveRec(LPCTSTR lpszNewValue);
	VARIANT GetKeyVal();
	void SetKeyVal(const VARIANT& newValue);
	long GetQItemType();
	void SetQItemType(long nNewValue);
	VARIANT GetRecord();
	void SetRecord(const VARIANT& newValue);
	CString GetRecordAttrib();
	void SetRecordAttrib(LPCTSTR lpszNewValue);
	short GetRecCount();
	void SetRecCount(short nNewValue);
	short GetRecNumber();
	void SetRecNumber(short nNewValue);
	long GetReplyRequested();
	void SetReplyRequested(long nNewValue);
	CString GetUserProf();
	void SetUserProf(LPCTSTR lpszNewValue);
	short GetRecLength();
	void SetRecLength(short nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_EIGDATAQUEUEITEMW_H__E746E134_B6CC_46EE_A29D_C81655753CD7__INCLUDED_)
