#if !defined(AFX_EIGDATAQUEUE_H__7FE2D578_A2C3_4A41_8AAE_755A3E291796__INCLUDED_)
#define AFX_EIGDATAQUEUE_H__7FE2D578_A2C3_4A41_8AAE_755A3E291796__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CEIGDataQueueItemW;

/////////////////////////////////////////////////////////////////////////////
// CEIGDataQueue wrapper class

class CEIGDataQueue : public COleDispatchDriver
{
public:
	CEIGDataQueue() {}		// Calls COleDispatchDriver default constructor
	CEIGDataQueue(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CEIGDataQueue(const CEIGDataQueue& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetQueueName();
	void AddQueueItem(LPDISPATCH QueueItem, long fBlock);
	void SetAttrib(long Attribute, const VARIANT& Value);
	void ClearAll(long Overwrite);
	void CreateQueue(short MaxMsgLength, long QAuthority, long QueueClass, long AddSenderInfo, short CCSID, short InitialSize, BOOL queueLoc, long recordLenCls, LPCTSTR Title, long AllowDupKeys, short MakeKeyLen);
	void DeleteQueue(long OverwriteData);
	CEIGDataQueueItemW GetQueueItem(long QueueType, long BlockComplete, long PeekQItem, long ProvideExtInfo, short TimeOut, long UserProfile, long SenderInfo, const VARIANT& SearchKey, long SearchOrder);
	void StopQueue();
	VARIANT QueryAttribute(long Attribute);
	void CancelQueue(short CancelReqCount, long CancelReqType, const VARIANT& KeyValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_EIGDATAQUEUE_H__7FE2D578_A2C3_4A41_8AAE_755A3E291796__INCLUDED_)
