#if !defined(AFX_EIGDATAQUEUECTL_H__BE67DE64_9112_4F31_9B5B_8C7B0C4AF3C6__INCLUDED_)
#define AFX_EIGDATAQUEUECTL_H__BE67DE64_9112_4F31_9B5B_8C7B0C4AF3C6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CEIGDataQueue;

/////////////////////////////////////////////////////////////////////////////
// CEIGDataQueueCtl wrapper class

class CEIGDataQueueCtl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CEIGDataQueueCtl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xfc478a0, 0xf77d, 0x11d2, { 0xa6, 0xb6, 0x0, 0x80, 0xc7, 0x1b, 0x80, 0x71 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetConnectionType();
	void SetConnectionType(long nNewValue);
	CString GetUserID();
	void SetUserID(LPCTSTR lpszNewValue);
	CString GetPassword();
	void SetPassword(LPCTSTR lpszNewValue);
	short GetPCCodePage();
	void SetPCCodePage(short nNewValue);
	short GetCcsid();
	void SetCcsid(short nNewValue);
	long GetConnectionState();
	CString GetLocalLU();
	void SetLocalLU(LPCTSTR lpszNewValue);
	CString GetRemoteLU();
	void SetRemoteLU(LPCTSTR lpszNewValue);
	CString GetModeName();
	void SetModeName(LPCTSTR lpszNewValue);
	CString GetNetAddr();
	void SetNetAddr(LPCTSTR lpszNewValue);
	CString GetNetPort();
	void SetNetPort(LPCTSTR lpszNewValue);
	void Connect();
	void Disconnect();
	CEIGDataQueue CreateQueueContainer(LPCTSTR BSTRQueueName);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_EIGDATAQUEUECTL_H__BE67DE64_9112_4F31_9B5B_8C7B0C4AF3C6__INCLUDED_)
