!include <disable.mak>

# THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
# ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED
# TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
# PARTICULAR PURPOSE.
#
# Copyright 1998 Microsoft Corporation.  All Rights Reserved.
#
# Processor independent makefile

DIRS = \
    dibview\~   \
    enumprof\~   \
    named\~   \

SDKPROJ = ICMSamples

!include <sdkpropbld.mak>

all: $(DIRS)

$(DIRS):
!include <sdkbld.mak>
