
/******************************************************************************\
********************************************************************************
* Filename: cpicturectl1.h
*
* Description:

	 Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++
	 NOTE: Do not modify the contents of this file.  If this class is regenerated by
	 Microsoft Visual C++, your modifications will be overwritten.

*
* This file is provided as part of the Microsoft Transaction Server
* Software Development Kit
*
*THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT 
*WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, 
*INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
*OF MERCHANTABILITY AND/OR FITNESS FOR A  PARTICULAR 
*PURPOSE.
*
* Copyright (C) 1997 - 2000 Microsoft Corporation, All rights reserved
********************************************************************************
\******************************************************************************/
#ifndef __CPICTURECTL1_H__
#define __CPICTURECTL1_H__


/////////////////////////////////////////////////////////////////////////////
// CNewPictureCtl wrapper class

class CNewPictureCtl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNewPictureCtl)
public:
	CLSID const& GetClsid()
	{

		//
		//	vb will change this CLSID every time it recompiles, so 
		//	we need to get it from the registry 
		//
		static CLSID clsid;		
		HRESULT hr;
		hr = CLSIDFromProgID(L"Picture.PictureCtl", &clsid);
		if (FAILED(hr))
		{
			AfxMessageBox(_T("PictureCtl.OCX is not properly registerd!"), MB_ICONSTOP);
		}
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	// method 'QueryInterface' not emitted because of invalid return type or parameter type
	unsigned long AddRef();
	unsigned long Release();
	// method 'GetTypeInfoCount' not emitted because of invalid return type or parameter type
	// method 'GetTypeInfo' not emitted because of invalid return type or parameter type
	// method 'GetIDsOfNames' not emitted because of invalid return type or parameter type
	// method 'Invoke' not emitted because of invalid return type or parameter type
	CString GetPictureFileName();
	void SetPictureFileName(LPCTSTR lpszNewValue);
};

#endif // __CPICTURECTL1_H__
