!include <disable.mak>

All:
!IFDEF NODEBUG
   nmake /f PoolTest.mak CFG="PoolTest - Win32 Unicode Release MinSize" -nologo /$(MAKEFLAGS) $(makeopts)
!ELSE
   nmake /f PoolTest.mak -nologo /$(MAKEFLAGS) $(makeopts)
!ENDIF