!include <disable.mak>

Proj= Hello3

libs= oleaut32.lib 

!include <BkOffice.mak>

ObjList =  $(ObjDir)\$(Proj).obj \
           $(ObjDir)\Notify.obj 

$(ObjDir)\$(Proj).exe: $(ObjList)        

all: $(ObjDir)\$(Proj).exe 
