<HTML>
    <HEAD>
        <TITLE>Index Server Component</TITLE>
    </HEAD>

    <BODY bgcolor="white" topmargin="10" leftmargin="10">
        
        <!-- Display Header -->

        <font size="4" face="Arial, Helvetica">
        <b>Index Server Component</b></font><br>   

	<hr size="1" color="#000000">

	
	Index Server now comes with a collection of components that can be used from
	Active Server Pages.  Please visit the Index Server Sample Site for examples
	demonstrating how to Index Server with ASP.

	<p><A href=/iissamples/issamples/> Click here to visit the Index Server Sample Site</A>
		
	</BODY>
</HTML>