!include <disable.mak>

All:
!IFDEF NODEBUG
   nmake /f VCSECURITYSAMPLE.MAK CFG="VCSecuritySample - Win32 Unicode Release MinSize" -nologo /$(MAKEFLAGS) $(makeopts)
!ELSE
   nmake /f VCSECURITYSAMPLE.MAK -nologo /$(MAKEFLAGS) $(makeopts)
!ENDIF