#if !defined(AFX_EIGFILETRANSFERCTL_H__BBE99CFC_286C_48CD_A62B_698132CA22A5__INCLUDED_)
#define AFX_EIGFILETRANSFERCTL_H__BBE99CFC_286C_48CD_A62B_698132CA22A5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CEIGFileTransferCtl wrapper class

class CEIGFileTransferCtl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CEIGFileTransferCtl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x35c0e97e, 0xca78, 0x11d2, { 0x81, 0x14, 0x0, 0x80, 0xc7, 0x1b, 0x80, 0x71 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetConnectionType();
	void SetConnectionType(long nNewValue);
	CString GetRDBName();
	void SetRDBName(LPCTSTR lpszNewValue);
	CString GetUserID();
	void SetUserID(LPCTSTR lpszNewValue);
	CString GetPassword();
	void SetPassword(LPCTSTR lpszNewValue);
	short GetPCCodePage();
	void SetPCCodePage(short nNewValue);
	short GetCcsid();
	void SetCcsid(short nNewValue);
	long GetConnectionState();
	CString GetLocalLU();
	void SetLocalLU(LPCTSTR lpszNewValue);
	CString GetRemoteLU();
	void SetRemoteLU(LPCTSTR lpszNewValue);
	CString GetModeName();
	void SetModeName(LPCTSTR lpszNewValue);
	CString GetNetAddr();
	void SetNetAddr(LPCTSTR lpszNewValue);
	CString GetNetPort();
	void SetNetPort(LPCTSTR lpszNewValue);
	void Connect();
	void Disconnect();
	void PutFile(LPCTSTR hostFile, LPCTSTR LocalFile);
	void GetFile(LPCTSTR LocalFile, LPCTSTR hostFile);
	void Cancel();
	CString GetHCDFile();
	void SetHCDFile(LPCTSTR lpszNewValue);
	long GetOverwriteHostFile();
	void SetOverwriteHostFile(long nNewValue);
	long GetAppendToEnd();
	void SetAppendToEnd(long nNewValue);
	long GetCreateIfNonExisting();
	void SetCreateIfNonExisting(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_EIGFILETRANSFERCTL_H__BBE99CFC_286C_48CD_A62B_698132CA22A5__INCLUDED_)
