/******************************************************************************
*
*  File: English.cpp
*
*  Author:  Joel Alley
*
*  Date: November 24, 1998
*
*  Description:   This file serves as a compile point for English.dll, which
*                 is a resource-only DLL that contains the message strings for
*                 english error messages in the sample script engine.
*
*  Modifications:
******************************************************************************/
