//--------------------------------------------------------------------
// Microsoft OLE DB Sample Provider
// (C) Copyright 1991 - 2000 Microsoft Corporation. All Rights Reserved.
//
// @doc
//
// @module GLOBALS.CPP | Global Initialization Object..
//
//

//  Make sure constants get initialized
#define INITGUID
#define DBINITCONSTANTS

// Includes ------------------------------------------------------------------
#include "headers.h"
