!include <disable.mak>

All:
!IFDEF NODEBUG
   nmake /f Account.mak CFG="Account - Win32 Release" -nologo /$(MAKEFLAGS) $(makeopts)
!ELSE
   nmake /f Account.mak -nologo /$(MAKEFLAGS) $(makeopts)
!ENDIF