!include <disable.mak>

All:
!IFDEF NODEBUG
   nmake /f Disp1.mak CFG="Disp1 - Win32 Release MinSize" -nologo /$(MAKEFLAGS) $(makeopts)
!ELSE
   nmake /f Disp1.mak -nologo /$(MAKEFLAGS) $(makeopts)
!ENDIF