//-----------------------------------------------------------------------------
//
// File:        StdAfx.cpp
//
// Copyright:   Copyright (c) 1991 - 2000 Microsoft Corporation
//
// Contents:    source file that includes just the standard includes
//
// Comments:    stdafx.pch will be the pre-compiled header
//              stdafx.obj will contain the pre-compiled type information
//
//-----------------------------------------------------------------------------

#include "stdafx.h"

#ifdef _ATL_STATIC_REGISTRY
#include <statreg.h>
#include <statreg.cpp>
#endif

#include <atlimpl.cpp>
