!include <disable.mak>

Proj= Hello

libs= oleaut32.lib 

!include <BkOffice.mak>

ObjList =  $(ObjDir)\$(Proj).obj  

$(ObjDir)\$(Proj).exe: $(ObjList)        

all: $(ObjDir)\$(Proj).exe 