<%@ LANGUAGE = VBScript %>
<%  Option Explicit     %>

<% 
	Response.ContentType = "text/html" 
%>


<HTML>
    <HEAD>
        <TITLE>ContentType Sample</TITLE>
    </HEAD>

    <BODY BGCOLOR="White" topmargin="10" leftmargin="10">

		<!-- Display Header -->

		<font size="4" face="Arial, Helvetica">
		<b>ContentType Sample</b></font>
      
		<hr size="1" color="#000000"><p>

		We have explicitly identified this page with
		the "text/html" MIME type.

    </BODY>
</HTML>
