!include <disable.mak>

All:
!IFDEF NODEBUG
   nmake /f Oledbkb.mak CFG="Oledbkb - Win32 Release MinSize" -nologo /$(MAKEFLAGS) $(makeopts)
!ELSE
   nmake /f Oledbkb.mak -nologo /$(MAKEFLAGS) $(makeopts)
!ENDIF