!include <disable.mak>

All:
!IFDEF NODEBUG
   nmake /f ADOKB.MAK CFG="ADOKB - Win32 Release MinSize" -nologo /$(MAKEFLAGS) $(makeopts)
!ELSE
   nmake /f ADOKB.MAK -nologo /$(MAKEFLAGS) $(makeopts)
!ENDIF