!include <disable.mak>

Proj= simple

console=1

!include <BkOffice.mak>

libs=$(libs) winfax.lib

ObjList =  $(ObjDir)\$(Proj).obj   \
           $(ObjDir)\$(Proj).res
 

all: $(ObjDir)\$(Proj).exe

$(ObjDir)\$(Proj).exe: $(ObjList) 

