<% @Language=JScript %>

<HTML>
    <HEAD>
        <TITLE>Server Side Includes</TITLE>
    </HEAD>

    <BODY bgcolor="white" topmargin="10" leftmargin="10">
        
        <!-- Display Header -->

        <font size="4" face="Arial, Helvetica">
        <b>Server Side Includes</b></font><br>   


		<p>Server Side Includes can be done using the
		#Include File command.  The below text in bold
		has been generated with a server side include:

		<p> <!--#INCLUDE FILE="HeaderInfo.asp"--> </p>
		
		<P> Include files can be referenced using either
		absolute or relative paths.<BR>
    </BODY>
</HTML>
