!include <disable.mak>

All:
!IFDEF NODEBUG
   nmake /f OPBank.mak CFG="OPBank - Win32 Release MinSize" -nologo /$(MAKEFLAGS) $(makeopts)
!ELSE
   nmake /f OPBank.mak -nologo /$(MAKEFLAGS) $(makeopts)
!ENDIF