!include <disable.mak>

Proj= Instcodc

!include <BkOffice.mak>

ObjList =  $(ObjDir)\$(Proj).obj  \
           $(ObjDir)\$(Proj).res

$(ObjDir)\$(Proj).exe: $(ObjList)        

all: $(ObjDir)\$(Proj).exe